name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    # inject env for build
    - name: Create env file
      run: |
        echo "${{ secrets.FRONTEND_ENV }}" > .env.production

    - name: Install deps
      run: npm ci

    - name: Build
      run: npm run build

    - name: Archive
      run: |
        tar -czf frontend.tar.gz \
        .next \
        public \
        package.json \
        package-lock.json \
        next.config.ts \
        .env.production

    - name: Upload to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: frontend.tar.gz
        target: /var/www/web-arasya-rentcar/

    - name: Deploy
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}

        script: |

          set -e

          export NVM_DIR="$HOME/.nvm"
          source $NVM_DIR/nvm.sh

          cd /var/www/web-arasya-rentcar

          PREVIOUS=$(readlink current || echo "")

          RELEASE=$(date +%Y%m%d%H%M%S)

          mkdir -p releases/$RELEASE

          tar -xzf frontend.tar.gz -C releases/$RELEASE

          # copy env to shared
          cp releases/$RELEASE/.env.production shared/.env

          ln -sfn releases/$RELEASE current

          cd current

          npm ci --omit=dev

          pm2 reload dashboard

          sleep 5

          if ! curl -f http://localhost:3000 > /dev/null; then

            echo "Rollback..."

            ln -sfn $PREVIOUS current

            pm2 reload dashboard

            exit 1

          fi

          echo "Deploy success"

          ls -dt releases/* | tail -n +6 | xargs rm -rf